// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPMW-b7yXUAiVsYtmmVEdxyYIiDICwGKA',
    appId: '1:1080345241386:web:ccee39345a954e15d3e053',
    messagingSenderId: '1080345241386',
    projectId: 'deliveryapp-6d0cc',
    authDomain: 'deliveryapp-6d0cc.firebaseapp.com',
    storageBucket: 'deliveryapp-6d0cc.firebasestorage.app',
    measurementId: 'G-P53EG33W5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7q_BGXNcFT4rDHI8EP15ilyyBlrsHla0',
    appId: '1:1080345241386:android:932f35beec67f708d3e053',
    messagingSenderId: '1080345241386',
    projectId: 'deliveryapp-6d0cc',
    storageBucket: 'deliveryapp-6d0cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-r8BHj8yMAlqGmx3F-zlNyhkLDtlpsF0',
    appId: '1:1080345241386:ios:9496cbd24a4dfa27d3e053',
    messagingSenderId: '1080345241386',
    projectId: 'deliveryapp-6d0cc',
    storageBucket: 'deliveryapp-6d0cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeployTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPMW-b7yXUAiVsYtmmVEdxyYIiDICwGKA',
    appId: '1:1080345241386:web:654e59e194aec1c2d3e053',
    messagingSenderId: '1080345241386',
    projectId: 'deliveryapp-6d0cc',
    authDomain: 'deliveryapp-6d0cc.firebaseapp.com',
    storageBucket: 'deliveryapp-6d0cc.firebasestorage.app',
    measurementId: 'G-9T8DC8LK31',
  );
}
